version: '3.4'
services:
    sonarqube:
        image: sonarqube:7.0
        hostname: sonarqube
        ports:
            - 9000:9000/tcp
            - 9092:9092/tcp
        networks:
            dcs:
        environment:
            - SONARQUBE_JDBC_USERNAME=userdcs
            - SONARQUBE_JDBC_PASSWORD=userdcs
            - SONARQUBE_JDBC_URL==jdbc:postgresql://postgres:5432/sonar
        volumes:
            - sonarqube_conf:/opt/sonarqube/conf
            - sonarqube_data:/opt/sonarqube/data
            - sonarqube_extensions:/opt/sonarqube/extensions
            - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
        logging:
            driver: json-file
            options:
                max-file: '3'
                max-size: 100m
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 1
                delay: 10s
            placement:
                constraints:
                    - node.role == worker
    postgres:
        image: postgres:10.3
        hostname: postgres
        ports:
            - 9000:9000/tcp
            - 9092:9092/tcp
        networks:
            dcs:
        environment:
            - POSTGRES_USER=sonar
            - POSTGRES_PASSWORD=sonar
        volumes:
            - postgresql:/var/lib/postgresql
            - postgresql_data:/var/lib/postgresql/data
        logging:
            driver: json-file
            options:
                max-file: '3'
                max-size: 100m
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 1
                delay: 10s
            placement:
                constraints:
                    - node.role == worker
networks:
    sonarqube:
        external: true
