version: 0.1
log:
  accesslog:
    disabled: true
  level: debug
  formatter: text
  fields:
    service: registry
    environment: staging
loglevel: debug
storage:
  oss:
    accesskeyid: xxxx
    accesskeysecret: xxxx
    region: oss-cn-shanghai
    bucket: xxxx
    # endpoint: optional endpoints
    # internal: optional internal endpoint
    # encrypt: optional data encryption setting
    # secure: optional ssl setting
    # chunksize: optional size valye
    # rootdirectory: optional root directory
  delete:
    enabled: true
  redirect:
    disable: false
  cache:
    blobdescriptor: redis
#auth:
#  token:
#    realm: http://192.168.31.136:8080/auth
#    service: "Docker registry"
#    issuer: "Auth Service"
#    rootcertbundle: /certs/hub.xmitd.com.crt
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
redis:
  addr: redis:6379
  db: 0
  dialtimeout: 10ms
  readtimeout: 10ms
  writetimeout: 10ms
  pool:
    maxidle: 16
    maxactive: 64
    idletimeout: 300s