version: '3.4'
services:
    registry:
        image: registry:2.6.1
        hostname: registry
        ports:
            - 5000:5000/tcp
        networks:
            registry:
                aliases:
                    - registry
        configs:
          - source: registryconfig
            target: /etc/docker/registry/config.yml
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                order: start-first
                parallelism: 1
                delay: 10s
        healthcheck:
            test: ["CMD-SHELL", "nc -z 127.0.0.1 5000 || exit 1"]
            interval: 10s
            timeout: 5s
            retries: 3
        logging:
            driver: json-file
            options:
                max-file: '3'
                max-size: 100m

    redis:
        image: redis:4.0.6
        networks:
            registry:
                aliases:
                    - redis
        volumes:
            - ./data/redis:/data:rw
            - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
        healthcheck:
            test: ["CMD-SHELL", "redis-cli -h 127.0.0.1 PING &> /dev/null || exit 1"]
            interval: 10s
            timeout: 5s
            retries: 3
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                order: stop-first
                parallelism: 1
                delay: 10s
        logging:
            driver: json-file
            options:
                max-file: '3'
                max-size: 100m

    minio:
        image: minio/minio:RELEASE.2018-09-01T00-38-25Z
        command: server /data
        networks:
            registry:
                aliases:
                    - minio
        environment:
            - MINIO_ACCESS_KEY=BR7F96JG3FWWKPSO7GQB
            - MINIO_SECRET_KEY=drHhl1rpsfBdxOEXQdUIw2uLaTsQqZElAFozNdGw
        volumes:
            - ./data/minio/data:/data:rw
            - ./data/minio/config:/root/.minio:rw
            - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                order: stop-first
                parallelism: 1
                delay: 10s
        logging:
            driver: json-file
            options:
                max-file: '3'
                max-size: 100m
configs:
    registryconfig:
        file: ./conf/config.yml
networks:
    registry:
        external: true